general.import = [ "~/.config/alacritty/themes/kanagawa.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

[font.bold]
style  = "Bold"

[font.italic]
style  = "Italic"

[font.bold_italic]
style  = "Bold Italic"

[window]
padding = { x = 14, y = 14 }
decorations = "None"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
